### PR TITLE
Make the images we run installation in look a little more realistic.

### PR DESCRIPTION
**Pull request by dlorenc**
The jobs now run as a non-root user in a real home directory.

### CODE REVIEW

**Review by naveensrinivasan — APPROVED** [review]
Nice, Would distroless images like these would be better of ?https://github.com/GoogleContainerTools/distroless/blob/master/examples/python3/Dockerfile
https://github.com/GoogleContainerTools/distroless/blob/master/examples/nodejs/Dockerfile

**Comment by jordan-wright** [comment]
Out of curiosity, what do we define as "realistic"? On one hand, we could say that we want these to look like a developer's laptop, but that might introduce things that are easier to fingerprint.

On the other hand, I've historically leaned towards "realistic" meaning what would likely be seen running in CI jobs at large organizations. To that end, I'd encourage keeping the Dockerfiles bland and boring, preferring the default images as-is wherever possible. That way there's no fingerprinting that can be done without also severely limiting the reach of the malware.

**Comment by dlorenc** [comment]
That's fair! I was actually trying to simulate "desktop/laptop" scenarios, where you're running as non root and you're worried about personal credentials.

The CI one is another threat model where the root is way more realistic like you said.

**Comment by dlorenc** [comment]
Opened https://github.com/ossf/package-feeds/issues/49 to track thinking through other ways to run these.

**Pull request merged**
